name = "PkgOptionsLoader"
uuid = "a1f74f29-89a2-4b0d-830c-4d59713831bd"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
